dw_slide_show:
    resource: "@DWSlideShowBundle/Resources/config/routing.yml"
    prefix:   /

dw_user:
    resource: "@DWUserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: AcmeSecurityBundle:Security:login }
login_check:
    pattern:   /login_check

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
